// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0TYFY7dzBZoqf8E0GkcDYt62fcl56nI',
    appId: '1:658477509030:web:3149fc7a59479038ccc767',
    messagingSenderId: '658477509030',
    projectId: 'connect-plus-student',
    authDomain: 'connect-plus-student.firebaseapp.com',
    databaseURL: 'https://connect-plus-student-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connect-plus-student.appspot.com',
    measurementId: 'G-SQT0QPVY4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB21J9bRDXwPOt2zzM-TjGlnFdkijOtv1c',
    appId: '1:658477509030:android:0e036874cb251f02ccc767',
    messagingSenderId: '658477509030',
    projectId: 'connect-plus-student',
    databaseURL: 'https://connect-plus-student-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connect-plus-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkqHCqM6nIFeyV1gyr9hnnPhUOYAhKYk',
    appId: '1:658477509030:ios:d0cba6084c17d2b1ccc767',
    messagingSenderId: '658477509030',
    projectId: 'connect-plus-student',
    databaseURL: 'https://connect-plus-student-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connect-plus-student.appspot.com',
    androidClientId: '658477509030-6u4itlrhhiemnkhl37st5fop068ersk8.apps.googleusercontent.com',
    iosClientId: '658477509030-i2vmvu61ef5n4joe445e5de6q6h9r2md.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectplusstudentadmin',
  );
}
